name: CNB

on:
  workflow_dispatch:
  push:
    branches: [ main ]  

jobs:
  sync-cnb:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: pushto
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/ADM25/37289551/cnb.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="37289551" \
            -e PLUGIN_PASSWORD="${{ secrets.CNB_TOKEN }}" \
            -e PLUGIN_BRANCH="main" \
            -e PLUGIN_FORCE="true" \
            tencentcom/git-sync

            
